from unittest import TestCase


class Test(TestCase):
    def test_after_request(self):
        self.fail()
